
services:
  qqbot:
    build: .
    container_name: qqbot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./.env:/app/.env

    networks:
      - qqbot-network



networks:
  qqbot-network:
    driver: bridge
